input_data_path: "data/raw/train.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"

splitting_params: 
  test_size: 0.15
  random_state: 42
train_params:
  model_type: "LogisticRegression"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "thal"
    - "ca"
  numerical_features:
    - "age"
    - "trestbps"
    - "thalach"
    - "oldpeak"
    - "chol"
target_col: "condition"